version: '2'
services:
  swat:
    image: dtr-sandbox.fusion.lmig.com/bcarpio/python_hello_world:0.0.12
    ports:
      - "8080"
    environment:
      WHO: 'Brian Carpio'
      WHAT: 'Is A Greenpages Consultant'
    networks:
      - helloworld
    container_name: swat

  nginx:
    image: dtr-sandbox.fusion.lmig.com/bcarpio/nginxplus
    ports:
      - "80"
    depends_on:
      - swat
    labels:
      interlock.hostname: "helloworld"
      interlock.domain: "example.com"
    networks:
      - helloworld
networks:
  helloworld:
